/**
 * Shared Pagefind engine plus the entity-facet and URL contract for the
 * archive's search UI.
 *
 * Imported by both the sidebar/hero preview (components/Search.astro) and the
 * full results page (pages/search.astro) so the index is fetched and
 * initialised once per document, no matter how many boxes are on the page.
 */

/** One hit's resolved fragment — only the fields the UI reads are typed. */
export interface PagefindHitData {
  url: string;
  /** Pagefind-generated HTML snippet with <mark> around the matched terms. */
  excerpt: string;
  meta: Record<string, string> & { title?: string };
}

/** A single result handle; `data()` lazily resolves the fragment. */
export interface PagefindHit {
  id: string;
  data(): Promise<PagefindHitData>;
}

export interface PagefindSearchResult {
  results: PagefindHit[];
  /** Total before the active filter, when Pagefind reports it. */
  unfilteredResultCount?: number;
}

export interface PagefindSearchOptions {
  /** Filter name → allowed values, e.g. `{ type: ['plugin'] }`. */
  filters?: Record<string, string[]>;
}

/** `filters()` → `{ type: { setup: 12, theme: 30, … } }`. */
export type PagefindFilterCounts = Record<string, Record<string, number>>;

export interface PagefindEngine {
  search(query: string, options?: PagefindSearchOptions): Promise<PagefindSearchResult>;
  filters(): Promise<PagefindFilterCounts>;
}

/** The runtime module also exposes the one-time setup calls. */
interface PagefindModule extends PagefindEngine {
  options(opts: { noWorker: boolean }): Promise<void>;
  init(): Promise<void>;
}

/** Results per page on /search/. */
export const PAGE_SIZE = 20;

/** Shortest query the engine runs; below this the UI stays idle. */
export const MIN_QUERY_LENGTH = 2;

/**
 * Entity-facet labels, in display order. The <select> only renders a type that
 * Pagefind reports in the live index (via `filters()`), so a label here with no
 * indexed page is simply never offered. The keys are the `type:` filter values
 * set at build time with `data-pagefind-filter`.
 */
export const TYPE_LABELS: Record<string, string> = {
  setup: 'Setups',
  guide: 'Guides',
  post: 'Posts',
  theme: 'Themes',
  plugin: 'Plugins',
  release: 'Releases',
  page: 'Pages',
};

/** Known facet values, in the order the UI shows them. */
export const TYPE_ORDER = Object.keys(TYPE_LABELS);

/** The `/search/` query contract, already normalised. */
export interface SearchState {
  /** Raw query with original case preserved. */
  q: string;
  /** Entity facet; '' means all types. */
  type: string;
  /** 1-based page. */
  page: number;
}

/** parseInt-normalise a page param: non-numeric, 0 or negative → 1. */
export function normalizePage(raw: string | null | undefined): number {
  const n = Number.parseInt(raw ?? '', 10);
  return Number.isFinite(n) && n >= 1 ? n : 1;
}

/** Clamp a requested page into the range a result set actually has. */
export function clampPage(page: number, total: number): number {
  const pages = Math.ceil(total / PAGE_SIZE);
  if (pages <= 0) return 1;
  return Math.min(Math.max(1, page), pages);
}

/** Read the query contract from a `location.search` string. */
export function parseState(search: string): SearchState {
  const params = new URLSearchParams(search);
  const type = params.get('type') ?? '';
  return {
    q: params.get('q') ?? '',
    // Unknown facets normalise to "all" rather than filtering on a value that
    // cannot exist — this also stops a hand-typed filter name reaching Pagefind.
    type: TYPE_ORDER.includes(type) ? type : '',
    page: normalizePage(params.get('page')),
  };
}

/** Build a canonical `/search/…` href from a state; omits defaults. */
export function buildSearchHref(state: SearchState): string {
  const params = new URLSearchParams();
  if (state.q) params.set('q', state.q);
  if (state.type) params.set('type', state.type);
  if (state.page > 1) params.set('page', String(state.page));
  const qs = params.toString();
  return qs ? `/search/?${qs}` : '/search/';
}

let enginePromise: Promise<PagefindEngine> | null = null;
let attempt = 0;

async function initEngine(cacheBust: string): Promise<PagefindEngine> {
  /*
   * Static import is impossible here: `/pagefind/pagefind.js` is generated by
   * `pagefind --site dist` AFTER the Astro build, so it does not exist at
   * author/build time and Vite must not try to resolve it. The specifier is
   * also runtime-selected — a retry appends a cache-buster because a browser
   * caches a failed module fetch by specifier, which would otherwise make the
   * "Try again" button replay the same rejection forever.
   */
  const specifier = `/pagefind/pagefind.js${cacheBust}`;
  const mod = (await import(/* @vite-ignore */ specifier)) as PagefindModule;
  // noWorker is required, not an optimisation: pagefind 1.5.2's shared worker
  // answers `init` and then never answers `search`, hanging the query. On the
  // main thread the whole search is <100ms for an index this size.
  await mod.options({ noWorker: true });
  await mod.init();
  return mod;
}

/**
 * The shared, lazy engine. One in-flight/resolved promise is reused by every
 * search box on the page. A rejected initialisation is cleared so the next call
 * — the retry button — starts a fresh attempt with a cache-busted specifier,
 * rather than resolving to the cached rejection.
 */
export function loadEngine(): Promise<PagefindEngine> {
  if (!enginePromise) {
    const cacheBust = attempt === 0 ? '' : `?retry=${attempt}`;
    attempt += 1;
    enginePromise = initEngine(cacheBust).catch((error) => {
      enginePromise = null;
      throw error;
    });
  }
  return enginePromise;
}
